name: Ansible
on: [ push, pull_request ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.x"

      - name: Install dependencies
        run: |
          pip install ansible ansible-lint
          ansible-galaxy collection install -r ansible/requirements.yml

      - name: Run ansible-lint
        working-directory: ansible
        run: ansible-lint .

      - name: Upload ansible artifact
        uses: actions/upload-artifact@v4
        if: ${{ !env.ACT }}
        with:
          name: ansible-artifact
          path: ${{ github.workspace }}/ansible


  molecule:
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        if: ${{ env.ACT }}

      - name: Download ansible artifact
        uses: actions/download-artifact@v4
        if: ${{ !env.ACT }}
        with:
          name: ansible-artifact
          path: .

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.x"

      - name: Install Molecule
        run: |
          pip install -r ansible/requirements-dev.txt
          ansible-galaxy collection install -r ansible/requirements.yml

      - name: Run Molecule tests
        working-directory: ansible/roles/web
        env:
          ANSIBLE_ALLOW_BROKEN_CONDITIONALS: "True"
        run: molecule test
